# Generated by Django 6.0.5 on 2026-05-18 12:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('payments', '0002_paymenttransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=40)),
                ('public_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('verification_hash', models.CharField(max_length=64)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='XAF', max_length=10)),
                ('payment_status_snapshot', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=220)),
                ('service_name', models.CharField(max_length=220)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_receipts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='organizations.organization')),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='payments.paymentrequest')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='payments.paymenttransaction')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('organization', 'receipt_number'), name='uniq_receipt_number_per_org')],
            },
        ),
    ]
