# Generated by Django 6.0.5 on 2026-05-18 11:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('MTN_MOMO', 'MTN Mobile Money'), ('CASH', 'Cash'), ('BANK_TRANSFER', 'Virement bancaire'), ('OTHER', 'Autre')], max_length=20)),
                ('operator', models.CharField(blank=True, max_length=50)),
                ('payer_phone', models.CharField(blank=True, max_length=20)),
                ('transaction_reference', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmee'), ('PENDING', 'En attente'), ('FAILED', 'Echouee'), ('CANCELLED', 'Annulee')], default='CONFIRMED', max_length=20)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payment_transactions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='organizations.organization')),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.paymentrequest')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('organization', 'transaction_reference'), name='uniq_transaction_reference_per_org')],
            },
        ),
    ]
